--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER_IN
--------------------------------------------------------

  CREATE TABLE "GENIE"."MEMBER_IN" 
   (	"M_ID" VARCHAR2(20 BYTE), 
	"M_NICKNAME" VARCHAR2(20 BYTE), 
	"M_PWD" VARCHAR2(20 BYTE), 
	"M_TEL" VARCHAR2(20 BYTE), 
	"M_ADDRESS" VARCHAR2(200 BYTE), 
	"M_EMAIL" VARCHAR2(50 BYTE), 
	"M_DATE" DATE, 
	"M_NO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER_OUT
--------------------------------------------------------

  CREATE TABLE "GENIE"."MEMBER_OUT" 
   (	"M_ID" VARCHAR2(20 BYTE), 
	"M_NICKNAME" VARCHAR2(20 BYTE), 
	"M_PWD" VARCHAR2(20 BYTE), 
	"M_TEL" VARCHAR2(20 BYTE), 
	"M_ADDRESS" VARCHAR2(200 BYTE), 
	"M_EMAIL" VARCHAR2(50 BYTE), 
	"M_DATE" DATE, 
	"M_NO" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GENIE.MEMBER_IN
SET DEFINE OFF;
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('mrg_1','백서진','0000','010','서울','aaa@aaa',to_date('20/04/01','RR/MM/DD'),1);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('jidong','서지수','tjwltn123*','010-3661-442','06267|서울 강남구 강남대로 238|123456789|null','tjwltn999@naver.com',to_date('20/04/14','RR/MM/DD'),109);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('kkkk','홍길동gg','Kkkk123!','010-000-000','06281|서울 강남구 대치동 670|ttt|null','bbb@naver.com',to_date('20/04/04','RR/MM/DD'),121);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('mmmm','커피','!cafein00','010-0000-0000','03906|서울 마포구 가양대로 124|1111|null','cafeinnnn@gmail.com',to_date('20/04/17','RR/MM/DD'),122);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('leess','이순신','1234','010','대구','ccc@ccc',to_date('20/04/05','RR/MM/DD'),102);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('_','_','_','010','_','_',null,-1);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('hong','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/04','RR/MM/DD'),101);
Insert into GENIE.MEMBER_IN (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('tngustngus','최수현','chltngus123*','010-1111-2222','13536|경기 성남시 분당구 백현동 582-7|789|null','tngustngus@naver.com',to_date('20/04/14','RR/MM/DD'),110);
REM INSERTING into GENIE.MEMBER_OUT
SET DEFINE OFF;
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('22','_','_','010','_','_',to_date('20/04/16','RR/MM/DD'),2);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('leess','이순신','1234','010','대구','ccc@ccc',to_date('20/04/16','RR/MM/DD'),102);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('22','_','_','010','_','_',to_date('20/04/16','RR/MM/DD'),2);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('22','_','_','010','_','_',to_date('20/04/16','RR/MM/DD'),2);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('22','_','_','010','_','_',to_date('20/04/16','RR/MM/DD'),2);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('kkkk','1234','Kkkk1234!','010-000-000','01214|서울 강북구 삼양로 90|tt|null','kkkk@naver.com',to_date('20/04/16','RR/MM/DD'),111);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('hhhh','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/16','RR/MM/DD'),111);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('kkkk','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/16','RR/MM/DD'),121);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('hhhh','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/16','RR/MM/DD'),111);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('kkkk','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/16','RR/MM/DD'),121);
Insert into GENIE.MEMBER_OUT (M_ID,M_NICKNAME,M_PWD,M_TEL,M_ADDRESS,M_EMAIL,M_DATE,M_NO) values ('hhhh','홍길동','1234','010','대전','bbb@bbb',to_date('20/04/16','RR/MM/DD'),111);
--------------------------------------------------------
--  DDL for Index SYS_C007177
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENIE"."SYS_C007177" ON "GENIE"."MEMBER_IN" ("M_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007178
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENIE"."SYS_C007178" ON "GENIE"."MEMBER_IN" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_IN
--------------------------------------------------------

  ALTER TABLE "GENIE"."MEMBER_IN" ADD UNIQUE ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GENIE"."MEMBER_IN" ADD PRIMARY KEY ("M_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GENIE"."MEMBER_IN" MODIFY ("M_PWD" NOT NULL ENABLE);
  ALTER TABLE "GENIE"."MEMBER_IN" MODIFY ("M_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "GENIE"."MEMBER_IN" MODIFY ("M_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_OUT
--------------------------------------------------------

  ALTER TABLE "GENIE"."MEMBER_OUT" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "GENIE"."MEMBER_OUT" MODIFY ("M_PWD" NOT NULL ENABLE);
  ALTER TABLE "GENIE"."MEMBER_OUT" MODIFY ("M_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "GENIE"."MEMBER_OUT" MODIFY ("M_ID" NOT NULL ENABLE);
