--------------------------------------------------------
--  파일이 생성됨 - 월요일-4월-20-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence REP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GENIE"."REP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table INFO_REPLY
--------------------------------------------------------

  CREATE TABLE "GENIE"."INFO_REPLY" 
   (	"REP_NUM" NUMBER(5,0), 
	"INFO_NO" NUMBER(5,0), 
	"CONT" NVARCHAR2(2000), 
	"WRITERNUM" NUMBER(5,0), 
	"DEP" NUMBER, 
	"PARENTNUM" NUMBER, 
	"REGDATE" DATE, 
	"R_CATEGORY" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into GENIE.INFO_REPLY
SET DEFINE OFF;
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (22,74,'나빠용',1,0,0,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (23,74,'나빠용!!!!',1,0,0,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (24,74,'나빠용',1,1,20,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (25,52,'오 감사합니다.',1,0,0,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (26,52,'네~~ ',1,1,25,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (27,51,'배고파요,,,',101,0,0,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (28,53,'좋아요!',1,0,0,to_date('20/04/16','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (29,10,'tttt',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (30,21,'gggggggg',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (31,2,'tttttt',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (32,2,'tttttt',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (33,1,'ttttt',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (34,18,'yyyy',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (35,18,'ggggggg',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (36,18,'gggg',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (37,18,'gggg',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (38,21,'심장이바운스빠운쓰',1,0,0,to_date('20/04/16','RR/MM/DD'),'정보광장');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (39,2,'바움스바웅느',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (40,2,'바움스바웅느',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (20,74,'나빠요',1,0,0,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (21,74,'나빠요!',1,1,20,to_date('20/04/14','RR/MM/DD'),null);
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (41,21,'ㅅㅅㅅㅅ',1,0,0,to_date('20/04/16','RR/MM/DD'),'정보광장');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (42,2,'ㅎㅎ',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (43,2,'ㅎㅎㅎ',1,0,0,to_date('20/04/16','RR/MM/DD'),'공지사항');
Insert into GENIE.INFO_REPLY (REP_NUM,INFO_NO,CONT,WRITERNUM,DEP,PARENTNUM,REGDATE,R_CATEGORY) values (44,22,'우와아아아앙아
',1,0,0,to_date('20/04/17','RR/MM/DD'),'정보광장');
--------------------------------------------------------
--  DDL for Index SYS_C007161
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENIE"."SYS_C007161" ON "GENIE"."INFO_REPLY" ("REP_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table INFO_REPLY
--------------------------------------------------------

  ALTER TABLE "GENIE"."INFO_REPLY" ADD PRIMARY KEY ("REP_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "GENIE"."INFO_REPLY" MODIFY ("INFO_NO" NOT NULL ENABLE);
